FROM quay.io/keycloak/keycloak:19.0.1

# Must add json files before import, volume is not mounted yet
COPY /src/Docker/KeycloakData /opt/keycloak/data/import/

# Import all files
RUN /opt/keycloak/bin/kc.sh import --dir=/opt/keycloak/data/import/ --override true; exit 0

# Start image
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "-v", "start-dev"]