import IISAsyncOpenXmlReportsSampleProducingCountryEController from '../i-i-s-async-open-xml-reports-sample-producing-country-e';

var IISAsyncOpenXmlReportsSampleProducingCountryENewController = IISAsyncOpenXmlReportsSampleProducingCountryEController;
export default IISAsyncOpenXmlReportsSampleProducingCountryENewController;
