FROM postgres:11.16

ENV POSTGRES_USER flexberryuser
ENV POSTGRES_PASSWORD jhv
ENV POSTGRES_DB appdb

COPY PostgreSql.create.sql /docker-entrypoint-initdb.d/
COPY PostgreSql.Security.create.sql /docker-entrypoint-initdb.d/
COPY PostgreSql.Security.insert.sql /docker-entrypoint-initdb.d/